version: "3.8"

services:

  instrument-service:
    build:
      context: ./instrument-service
    container_name: instrument-service
    ports:
      - "8081:8081"
    networks:
      - laboratory-network

  experiment-service:
    build:
      context: ./experiment-service
    container_name: experiment-service
    ports:
      - "8082:8082"
    networks:
      - laboratory-network

  frontend:
    build:
      context: ./frontend
    container_name: laboratory-frontend
    ports:
      - "8080:80"
    networks:
      - laboratory-network

networks:
  laboratory-network:
    driver: bridge
